import "server-only";

import {
  createCipheriv,
  createDecipheriv,
  hkdfSync,
  randomBytes,
} from "node:crypto";

/**
 * Encryption for secrets we hold on a user's behalf.
 *
 * MCP auth headers are bearer tokens for someone else's system. Storing them in
 * plain text would mean a database dump is enough to act as our users against
 * third parties, so they are encrypted at rest.
 *
 * The key is derived from BETTER_AUTH_SECRET rather than configured separately.
 * That secret already exists, is already required, and is already generated by
 * the quickstart — a second key would be one more thing to forget, and a
 * forgotten encryption key tends to be discovered in production. HKDF with a
 * distinct info string means this key is not the session-signing key, so
 * neither use can be exploited through the other.
 */

const ALGORITHM = "aes-256-gcm";
const IV_BYTES = 12; // GCM's standard nonce length.
const KEY_INFO = "terrablox:secret-box:v1";

let cachedKey: Buffer | null = null;

function key(): Buffer {
  if (cachedKey) return cachedKey;

  const secret = process.env.BETTER_AUTH_SECRET?.trim();

  // Failing loudly here beats encrypting with a default: a predictable key
  // looks exactly like a real one until someone reads the code.
  if (!secret) {
    throw new Error(
      "BETTER_AUTH_SECRET is not set, so secrets cannot be encrypted.",
    );
  }

  cachedKey = Buffer.from(
    hkdfSync("sha256", secret, "terrablox", KEY_INFO, 32),
  );

  return cachedKey;
}

/**
 * Encrypts to `iv.ciphertext.tag`, all base64url.
 *
 * The IV is random per call and stored alongside, which is what makes it safe
 * to encrypt the same value twice. The tag is what makes tampering detectable.
 */
export function encryptSecret(plaintext: string): string {
  const iv = randomBytes(IV_BYTES);
  const cipher = createCipheriv(ALGORITHM, key(), iv);

  const ciphertext = Buffer.concat([
    cipher.update(plaintext, "utf8"),
    cipher.final(),
  ]);

  return [iv, ciphertext, cipher.getAuthTag()]
    .map((part) => part.toString("base64url"))
    .join(".");
}

/**
 * Returns null instead of throwing when a value cannot be read back.
 *
 * A row encrypted under an older secret is not a crash: the agent should still
 * run, just without that server's tools. Callers decide what to tell the user.
 */
export function decryptSecret(payload: string): string | null {
  try {
    const [ivPart, dataPart, tagPart] = payload.split(".");
    if (!ivPart || !dataPart || !tagPart) return null;

    const decipher = createDecipheriv(
      ALGORITHM,
      key(),
      Buffer.from(ivPart, "base64url"),
    );
    decipher.setAuthTag(Buffer.from(tagPart, "base64url"));

    return Buffer.concat([
      decipher.update(Buffer.from(dataPart, "base64url")),
      decipher.final(),
    ]).toString("utf8");
  } catch {
    return null;
  }
}
